baseurl = "http://www.example.com" # Hostname (and path) to the root.
title = "Ricardo Ortega" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Ricardo Ortega" # Author's name.
    info = "Software Developer" # Author's job title or info.
    description = "Ricardo Ortega's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/rj-fitz-roy.png" # Contain the path of the optional avatar in the static folder.

    footercontent = "Hello There." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/rj-ortega"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/rj-ortega/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"
[[menu.main]]
    name = "Projects"
    weight = 2
    url  = "projects"