baseurl = "https://rj-ortega.dev" # Hostname (and path) to the root.
title = "Ricardo J Ortega" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Ricardo Ortega" # Author's name.
    info = "Software Developer" # Author's job title or info.
    description = "Ricardo Ortega's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/rj.png" # Contain the path of the optional avatar in the static folder.

    footercontent = "Hello there." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = [
        "css/custom.css"
    ]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/rj-ortega/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/rj-ortega"
[[params.social]]
    name = "Resume"
    icon = "far fa-file-alt"
    weight = 1
    url = "https://drive.google.com/file/d/1sdRcrf0dBHM_xSzXzDiRtN9rjOI6QzyU/view"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 5
    url = "https://www.instagram.com/ricardo_ortega/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"
[[menu.main]]
    name = "Projects"
    weight = 2
    url  = "projects"